ublox_gps_node:
  ros__parameters:
    debug: 0                    # 0-4 (0 means no debug statements)
    device: /dev/ttyACM0
    frame_id: gps
    uart1:
      baudrate: 115200
      out: 0
    tmode3: 0                   # Disable survey-in mode

    inf:
      all: true                 # Whether to display all INF messages in console
    
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false

    gnss:
      glonass: true
      beidou: true
      galileo: true
