ublox_gps_node:
  ros__parameters:
    debug: 0
    device: /dev/ttyACM0
    frame_id: gps
    rate: 4.0
    nav_rate: 1

    tmode3: 0
    sv_in.reset: false

    gnss.glonass: true
    gnss.beidou: true
    gnss.galileo: true

    inf.all: true
    
    publish.all: true
    publish.aid.hui: false
    publish.nav.posecef: false
